apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: evaou/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.tsx"
            dest: .
    - image: evaou/comments
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.ts"
            dest: .
    - image: evaou/event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.ts"
            dest: .
    - image: evaou/moderation
      context: moderation
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.ts"
            dest: .
    - image: evaou/posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.ts"
            dest: .
    - image: evaou/query
      context: query
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.ts"
            dest: .
